public class datas {
    public Integer id{get;set;}
    public String status{get;set;}
    public String firstName{get;set;}
    public String lastName{get;set;}
    public String street1{get;set;}
    public String city{get;set;}
    public String state{get;set;}
    public String zip{get;set;}
    public String notes{get;set;}
    public String userName{get;set;}
    public String userId{get;set;}
    public String dateModified{get;set;}
}