public class DiacoAppointmentHomeFields {

    public static Map<String,String> getRelatoFields() {

        Map<String,String> relatoFields = new Map<String,String>();

        // Home Automation 
        relatoFields.put(
            'Number_of_Entry_Exit_Doors__c',
            'of_Entry_Exit_Doors__c'
        );
        
        relatoFields.put(
            'RMR_Verified__c',
            'RMR_Verified__c'
        );
        
        relatoFields.put(
            'X99_Activation_Fee_Verified__c',
            'X99_Activation_Fee_Verified__c'
        );
        
        relatoFields.put(
            'Do_you_have_a_Doorbell_Camera__c',
            'Do_you_have_a_doorbell_camera__c'
        );

        relatoFields.put(
            'Existing_Contract__c',
            'Existing_Contract__c'
        );

        relatoFields.put(
            'Existing_Keypad__c',
            'Existing_Keypad__c'
        );

        relatoFields.put(
            'Months_Remaining__c',
            'Months_Remaining__c'
        );

        //Water Filtration
        relatoFields.put(
            'Avg_Monthly_Spend_on_Bottled_Water__c',
            'Bottled_Water__c'
        );
        
        //Solar - error de tipo
        /*relatoFields.put(
            'Account_YearHome_Built__c',
            'Year_Home_Built__c'
        );*/
        
        relatoFields.put(
            'Solar__c',
            'Solar__c'
        );
        
        relatoFields.put(
            'Energy_Efficiencies__c',
            'Energy_Efficiencies__c'
        );
        
       	relatoFields.put(
            'Shutters__c',
            'Shutters__c'
        );
        
        relatoFields.put(
            'House_Sq_Footage__c',
            'House_Square_Footage_Text__c'
        );
        /*error de tipo
        relatoFields.put(
            'Account_NumberAC_Units__c',
            'AC_Units__c'
        );**/
        relatoFields.put(
            'Avg_Temperature_AC_Kept_at__c',
            'Avg_Temperature_AC_Kept_at__c'
        );
        relatoFields.put(
            'Avg_Electric_Bill__c',
            'Average_Electric_Bill_Text__c'
        );
        relatoFields.put(
            'Credit_Score__c',
            'Credit_Score_Text__c'
        );
        
        //Pets
        relatoFields.put(
            'Pets__c',
            'Pets__c'
        );

        relatoFields.put(
            'Backyard_gate_locked__c',
            'Kept_Locked__c'
        );
        relatoFields.put(
            'Types_of_Pets__c',
            'Kinds_Of_Pets__c'
        );
        
        relatoFields.put(
            'Pest_loose_in_backyard__c',
            'Pets_Running_Loose_Backyard__c'
        );
		
        relatoFields.put(
            'Under_Contract__c',
            'Under_Contract__c'
        );
		
        
        relatoFields.put(
            'Already_have_a_system__c',
            'Already_have_a_system__c'
        );

        relatoFields.put(
            'Appointment_Setter__c',
            'ApptSetter__c'
        );

        relatoFields.put(
            'Cable_Satellite__c',
            'Cable_Satellite__c'
        );
              
        relatoFields.put(
            'Gate_to_Backyard__c',
            'Gate_to_Backyard__c'
        );
        
        relatoFields.put(
            'Lead_Source__c',
            'Lead_Source__c'
        );
        
        relatoFields.put(
            'Main_Area_of_Concern__c',
            'Main_Area_of_Concern__c'
        );
        
        relatoFields.put(
            'Pets_over_45_LBS__c',
            'Pets_over_45_LBS__c'
        );
        
        relatoFields.put(
            'Pre_plumbing__c',
            'Pre_Plumb__c'
        );
        
        relatoFields.put(
            'Cell_Phone_Type__c',
            'Cell_Phone_Type__c'
        );
        
        relatoFields.put(
            'Utility_Provider__c',
            'Utility_Company__c'
        );
        
        relatoFields.put(
            'Electric_Company__c',
            'Electric_Company__c'
        );
       
        relatoFields.put(
            'Windows__c',
            'Windows__c'
        );
        
        relatoFields.put(
            'Lead_Review__c',
            'Lead_Review__c'
        );
        
        relatoFields.put(
            'Number_of_people_over_12__c',
            'of_people_over_12_Home_Automation__c'
        );
        
        relatoFields.put(
            'Number_of_cell_phone_owners__c',
            'of_people_with_their_own_cell_phone__c'
        );
        
        relatoFields.put(
            'Payment_Type__c',
            'Payment_Type__c'
        );

        relatoFields.put(
            'Sub_Categories__c',
            'Sub_Categories__c'
        );

                
        relatoFields.put(
            'Channel_Source__c',
            'Channel_Source__c'
        );
        
        return relatoFields;

    }
}