/************************************************************************************************************
Created By : MST Solutions
Created Date : Dec/28/2015
Description : This controller used to display OB Call Center Screen Pop scripts dynamically.s 
Once the user submits appointment details, it will update OB Campaign Member record and It would create new Inventory records.
If user submits [Additional Interest] button, it will allow user to create additional interest inventory records. 
[Summary] button will display the inventory records list. If user submit confirmed, it won't take any action for those inventories.
If user select any industries and submits [Remove] button, it will update those industries as 'Non - Billable'.
**********************************************************************************************************************/


public class nuHome_Outbound_Beta_AC{
    public nuHome_Outbound_Beta_AC(){}
}