@isTest
public class nuHome_Outbound_Beta_AC_Test{
    /* Created By : MST Solutions
     * Created Date : Jan/01/2016
     * Description : This test class created for nuHome_Outbound_Beta_AC apex class.
     * */
    /************  updateAppointment **************/
    public static testMethod void updateAppointment(){    
		nuHome_Outbound_Beta_AC testIns	=	New nuHome_Outbound_Beta_AC();
        nuHome_Outbound_Util testIns2	=	New nuHome_Outbound_Util();
    }
    
}