/*
 * Diaco
 * @author             William Aldana
 * Project:            PB consolidation
 * TestClass:          N/A
 * Description:        Test Class
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    25/11/2020         William Aldana          Initial implementation of the class.
 **/
@isTest
public class PBBypassClassTest {
    @istest static void PBBypassClassTest() {
        PBBypassClass.ExecNothing();
    }
}