/*
 * Diaco
 * @author             William Aldana
 * Project:            PB consolidation
 * TestClass:          PBBypassClassTest
 * Description:        Invocable do nothing for PB avoid
 *
 * Changes (Version)
 * _________________________________________
 *            No.        Date            Author                    Description
 *            ____    __________        __________________      _____________________________________
 * @version   1.0    25/11/2020         William Aldana          Initial implementation of the class.
 **/
public class PBBypassClass {
    /**
    * @description This method will be executed to avoid PB execution
    * @author William Aldana | 11-25-2020 
    **/
    @InvocableMethod
    public static void ExecNothing() {

    }
}