@isTest
public class SendtoStrideTest {
    /*
    @isTest static void testStride() {
        settings_page__c v =  new settings_page__c();
        v.Name = 'test1';
        v.Chat_App_Token__c = 'ZCHNo7WBTfcCSfrgD2a9';
        v.Site_id__c = '67c76118-6b02-4b27-af6f-86ce6f685344';
        v.Chat_id__c = '1fa8263c-e543-445a-9542-2a387c44f685';
        Database.insert(v);
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new StrideHttpCalloutMock());
            List<String> paramList = new List<String>();
            paramList.add('test1,This is a Salesforce test');
            SendToStride.SendMessage(paramList);
            paramList[0] = '';
            SendToStride.SendMessage(paramList);
        Test.stopTest();
    }    */

}