@isTest
private class SettingsPageTest {
    /*
    @isTest static void Test(){
       settings_page__c v =  new settings_page__c();
       v.Chat_App_Token__c = 'ZCHNo7WBTfcCSfrgD2a9';
       v.Site_id__c = '67c76118-6b02-4b27-af6f-86ce6f685344';
       v.Chat_id__c = '1fa8263c-e543-445a-9542-2a387c44f685';
       Database.insert(v);
       Settings_page sp = new Settings_page(); 
       sp.NewChat.Chat_App_Token__c = 'ZCHNo7WBTfcCSfrgD2a9';
       sp.NewChat.Site_id__c = '67c76118-6b02-4b27-af6f-86ce6f685344';
       sp.NewChat.Chat_id__c = '1fa8263c-e543-445a-9542-2a387c44f685';
       sp.saveRecord();
       sp.UpdateSiteId();
       sp.getNewChat();
       sp.SelectedChatId =v.Id;
       sp.DeleteChat();
       sp.closePopup();
       sp.showPopup();
       
    } 
    @isTest static void Test2(){
       
       Settings_page sp = new Settings_page(); 
       sp.NewChat.Chat_App_Token__c = 'ZCHNo7WBTfcCSfrgD2a9';
       sp.NewChat.Site_id__c = '67c76118-6b02-4b27-af6f-86ce6f685344';
       sp.NewChat.Chat_id__c = '1fa8263c-e543-445a-9542-2a387c44f685';
       sp.saveRecord();
       sp.DeleteChat(); 
    } 
    @isTest static void Test3(){
       
       settings_page__c v =  new settings_page__c();
       v.Chat_App_Token__c = 'ZCHNo7WBTfcCSfrgD2a9';
       v.Site_id__c = '67c76118-6b02-4b27-af6f-86ce6f685344';
       v.Chat_id__c = '1fa8263c-e543-445a-9542-2a387c44f685';
       Database.insert(v);
       Settings_page sp = new Settings_page();
       sp.SelectedChatId =v.Id;
       sp.DeleteChat(); 
    } */
    
}